use_frameworks!
platform :ios, "13.0"

target "Halley_Example" do
  pod "Halley/Codable", :path => "../"
  pod "Alamofire"

  target "Halley_Tests" do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "13.0"
      config.build_settings["ARCHS"] = "$(ARCHS_STANDARD_64_BIT)"
    end
  end
end
