platform :ios, '15.0'

use_frameworks!
inhibit_all_warnings!

workspace '../../Halley.xcworkspace'

target 'HalleyCocoaPodExample' do
  pod 'Halley', :git => 'git@github.com:infinum/Halley.git', :branch => 'feature/swift-macros'
  pod 'HalleyMacro', :git => 'git@github.com:infinum/Halley.git', :branch => 'feature/swift-macros'
end
