# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Run Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-26
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_26.0.app
    
    - name: Build
      run: swift build
    
    - name: Run tests
      run: swift test
